//
// Created by huacheng on 1/12/22.
//

#include "test.h"


int test_aneos(FILE * output, const char * aname, int correct)
{
    // an example for aneos
    struct ANEOSTable eos_test;
    FILE * fp = fopen(aname,"r");
    LoadANEOS(&eos_test,fp);

//    double t = ANEOSInterpolateTP(&eos_test,293,1.0,-1);
    switch (correct) {
        case WITHOUTCORRECT:
            break;
        case CONSTSHIFT:
            ANEOSLowDenCorrect(&eos_test,10.0);
            break;
        default:
            break;
    }

    for(int k=0;k<21;k++)
    {
        for(int j=0;j<22;j++)
        {
            double kDen = 200.0 + 200.0*k;
            double jTmp = 275.0 + 200.0*j;
            double rPre = ANEOSInterpolateTD(&eos_test,jTmp,kDen,ANEOSPRE);
            fprintf(output,"%13.5e,",rPre);
        }
        fprintf(output,"\n");
    }

    UnAllocateANEOS(&eos_test);
    return 0;
}

int test_tillotson(FILE * output,const char * tname)
{
    struct TillotsonTable eos_test;
    FILE * fp = fopen(tname,"r");
    LoadTillEOS(&eos_test,fp);

    for(int k=0;k<21;k++)
    {
        for(int j=0;j<22;j++)
        {
            double kDen = 5.0 + 200.0*k;
            double jTmp = 275.0 + 200.0*j;
            double rPre = TillEOSInterpolateTD(&eos_test,jTmp,kDen,ANEOSCSD);
            fprintf(output,"%13.5e,",rPre);
        }
        fprintf(output,"\n");
    }

    UnAllocateTillEOS(&eos_test);
    return 0;
}




void test_pressure(struct ANEOSTable * _a,FILE * output,char * fmt, int lines)
{

    fprintf(output,"%d,%d,",_a->nTem,_a->nDen);
    fprintf(output,"\n");

    for(int k=0;k<_a->nTem;++k)
    {
        fprintf(output,fmt,_a->xTem[k]);
    }
    fprintf(output,"\n");

    for(int k=0;k<_a->nDen;++k)
    {
        fprintf(output,fmt,_a->yDen[k]);
    }
    fprintf(output,"\n");

    for(int k=0;k<_a->nTem;++k)
    {
        for(int j=0;j<_a->nDen;++j)
        {
            fprintf(output,fmt,_a->Data[k][j][1]);
        }
        fprintf(output,"\n");
    }
}

void test_pressure_example()
{
    test_aneos(stdout,"../data/granit2.aneos",CONSTSHIFT);
    struct ANEOSTable eos_test;
    FILE * fp = fopen("../data/granit2.aneos","r");
    LoadANEOS(&eos_test,fp);
    FILE * out = fopen("granit2.pre","w");

    test_pressure(&eos_test,out,"%12.5e,",20);

    UnAllocateANEOS(&eos_test);
    fclose(out);
}


void generate_aneos(const char * aname, int correct, const char * cname, const char *comment)
{
    // an example for aneos
    struct ANEOSTable eos_test;
    FILE * fp = fopen(aname,"r");
    LoadANEOS(&eos_test,fp);

    switch (correct) {
        case WITHOUTCORRECT:
            break;
        case CONSTSHIFT:
            ANEOSLowDenCorrect(&eos_test,10.0);
            break;
        default:
            break;
    }

    ANEOSWrite_2d(&eos_test,cname,comment);
    UnAllocateANEOS(&eos_test);
}

void special_scientific_notation(char * dst,unsigned int w,unsigned int d,double num)
{
    int num_exp = (int) ceil(log10(fabs(num)));
    double num_base   = num/ pow(10.,num_exp);

    if(fabs(num_base) >= 1.0)
    {
        num_base *= 0.1;
        num_exp  += 1;
    }

    char fmt_coeff_exp[20];
    sprintf(fmt_coeff_exp,"%%.%dfE%%+03d",d);
    sprintf(dst,fmt_coeff_exp,num_base,num_exp);
}

void fspecial_scientific_notation(FILE * fp, int w, int d,double num)
{
    int num_exp = (int) ceil(log10(fabs(num)));
    double num_base   = num/ pow(10.,num_exp);

    if(fabs(num_base) >= 1.0)
    {
        num_base *= 0.1;
        num_exp  += 1;
    }

    char fmt_coeff_exp[20];
    char out_num[100];
    sprintf(fmt_coeff_exp,"%%.%dfE%%+03d",d);
    sprintf(out_num,fmt_coeff_exp,num_base,num_exp);
    fprintf(fp,"%*s",w,out_num);
}

void ANEOSWrite_2d(struct ANEOSTable * _t,const char fname[], const char comment[] )
{
    // remove "\n" in comment
    // ...
    //
    FILE * fp = fopen(fname,"w");
    fprintf(fp,"#ANTAB\n"
               "# generated by EoSTool\n"
               "# %s\n",comment);
    // write the rows and columns of aneos table
    fprintf(fp,"%15d %15d\n",_t->nTem,_t->nDen);
    // set the normal state (T0,RHO0,P0)
//    fprintf(fp,"%22.15e %22.15e %22.15e\n",_t->Tnorm,_t->Dnorm,_t->Pnorm);
    fspecial_scientific_notation(fp,20,12,_t->Tnorm);
    fspecial_scientific_notation(fp,20,12,_t->Dnorm);
    fspecial_scientific_notation(fp,20,12,_t->Pnorm);
    fprintf(fp,"\n");

    // write the rows (Temperature)
    int WriteCounter = 0;
    for(int k=0;k<_t->nTem;++k)
    {
//        fprintf(fp,"%22.15e ",_t->xTem[k]);
        fspecial_scientific_notation(fp,20,12,_t->xTem[k]);
        if(++WriteCounter%4 == 0) fprintf(fp,"\n");
    }

    // write the data (Internal energy, pressure, speed of sound)
    for(int k=0;k<_t->nTem;++k)
    {
        for(int j=0;j<_t->nDen;++j)
        {
//            fprintf(fp,"%22.15e ",_t->Data[k][j][0]/_t->yDen[j]);
            fspecial_scientific_notation(fp,20,12,_t->Data[k][j][0]/_t->yDen[j]);
            if(++WriteCounter%4 == 0) fprintf(fp,"\n");
//            fprintf(fp,"%22.15e ", _t->Data[k][j][1]);
            fspecial_scientific_notation(fp,20,12,_t->Data[k][j][1]);
            if(++WriteCounter%4 == 0) fprintf(fp,"\n");
//            fprintf(fp,"%22.15e ",_t->Data[k][j][2]);
            fspecial_scientific_notation(fp,20,12,_t->Data[k][j][2]);
            if(++WriteCounter%4 == 0) fprintf(fp,"\n");
        }
    }

    // write the columns (Density)
    for(int k=0;k<_t->nDen;++k)
    {
//        fprintf(fp,"%22.15e",_t->yDen[k]);
        fspecial_scientific_notation(fp,20,12,_t->yDen[k]);
        if(++WriteCounter%4 == 0) fprintf(fp,"\n");
    }
    fclose(fp);
}

